### PR TITLE
Use % instead of [[ for finding the opening brace

### PR DESCRIPTION
**Pull request by dkasak**
[[ will only match opening braces that are located in the first column which makes af and if work incorrectly with other brace positioning styles. This commit switches to % instead which will always find the matching brace.

This seems to pass your current tests (it took some time to install the whole test toolchain successfully :D). I didn't want to write any new tests since I'm still not very familiar with the test toolchain.

### CODE REVIEW

**Comment by kana** [comment]
I don't believe the change is right.  How about the following code?

``` c
int foo(void)
{
    while (true)
    {
        foo();  /* the cursor is here. */
    }
}
```

**Comment by kana** [comment]
And I documented about [the expected brace style](https://github.com/kana/vim-textobj-function/blob/6fb7e9400ae033842c87ca9c596ccfae1aa29d5c/doc/textobj-function-c.txt#L74-L85).  In other words, I don't want to support other styles at the moment.  Additionally, your pull request doesn't update the document.

**Comment by dkasak** [comment]
Your example works as expected (i.e. `af` refers to the whole function, including the prototype line and `if` refers to the body of the function, excluding the braces). Why do you think it's wrong?

I could update the pull request to change the document. Of course, if you really feel strongly about not supporting other brace styles, I'll just use my own fork.

**Comment by kana** [comment]
Another example:

``` c

int foo(void)
{
    while (1)
    {
        // {{{  the cursor is here
    }
}
```

**Comment by dkasak** [comment]
Actually, this is where it breaks (it doesn't get the return type):

```
int 
foo(int a, 
    int b) {
    bar; /* cursor here */
}
```

Of course, the old code is also somewhat broken in this case, since in signatures where the return type is on the same line as the prototype it eats up an additional newline above the prototype, whereas in signatures such as this one, it doesn't. Also, it breaks on multiline signatures where there is whitespace right of the `)`, but I think that already falls under [this](https://github.com/kana/vim-textobj-function/blob/6fb7e9400ae033842c87ca9c596ccfae1aa29d5c/doc/textobj-function-c.txt#L83).

**Pull request closed without merging**
