### PR TITLE
Add Java support

### PR DESCRIPTION
**Pull request by janlarres**
Here is a patch that adds support for Java methods.

### CODE REVIEW

**Comment by janlarres** [comment]
I have improved the implementation by using the existing `]M`/`[m` motions, so it should hopefully be quite accurate now. Please take a look.

**Comment by kana** [comment]
Thank you.  I'll look into it later.
By the way, would you mind adding test cases for Java code?

**Comment by janlarres** [comment]
Okay I've added some tests and fixed a few small issues I found in the process.
By the way, I noticed that for the 'a' objects you don't select empty lines after the functions, like what for example the 'ap' object does. Is that intentional? I think it would be more consistent with Vim's normal text objects to include the empty lines.

**Comment by kana** [comment]
> Okay I've added some tests and fixed a few small issues I found in the process.

Thank you.  I'll merge it later.

> By the way, I noticed that for the 'a' objects you don't select empty lines after the functions, like what for example the 'ap' object does. Is that intentional? I think it would be more consistent with Vim's normal text objects to include the empty lines.

Yes, it is intentional.  Vim's built-in text objects can be classified into two groups.  Some text objects like `ap`/`ip` include also leading/trailing spaces, while other text objects like `at`/`it` don't include such spaces.  When I began to write vim-textobj-function, I thought these text objects are classified into the latter group.

But it might be better to provide also a variant of function text objects as you suggest, and to let users choose which variant to use.

**Pull request closed without merging**
